Fixing that naming of v1.12.4+ of docker-engine packages also contain…
mzedeler/dsh pull request #3
Opened 2017-01-05 12:29 UTC by CheMical

… name of linux distro.

2017-01-05 12:46 UTC, mzedeler commented
Hi :-)

I'll take a look :-)

2017-01-05 12:49 UTC, mzedeler requested changes

2017-01-05 12:49 UTC, mzedeler commented on dsh
> +        DOCKER_PACKAGE=${OPT_DOCKER_PACKAGE-docker-engine=$DOCKER_VERSION-0~$PHUSION_DIST$PHUSION_VERSION}
Rewrite to `$PHUSION_DIST-$PHUSION_VERSION` and remove the dash above.

2017-01-05 12:49 UTC, mzedeler commented on dsh
> +        PHUSION_DIST=$(dpkg --compare-versions 1.12.4 le $DOCKER_VERSION && docker run --rm phusion/baseimage lsb_release -is | awk '{print tolower($0)"-"}')
What does this fallback to if the version is above 1.12.4?

2017-01-06 11:55 UTC, CheMical commented on dsh
> +        PHUSION_DIST=$(dpkg --compare-versions 1.12.4 le $DOCKER_VERSION && docker run --rm phusion/baseimage lsb_release -is | awk '{print tolower($0)"-"}')
Default to the same as 1.12.4 (ubuntu-):
dpkg --compare-versions 1.12.4 le $DOCKER_VERSION
1.12.4 <= $DOCKER_VERSION

1.12.3 and below

2017-01-06 11:55 UTC, CheMical commented on dsh
> +        DOCKER_PACKAGE=${OPT_DOCKER_PACKAGE-docker-engine=$DOCKER_VERSION-0~$PHUSION_DIST$PHUSION_VERSION}
That would be nice and short, but the version of docker-engine depends on the host.

From https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/filelist you get that docker-engine packages are named differently starting with version 1.12.4. So package with version 1.12.3 is named ~xenial_amd64.deb and package with version 1.12.4 and above is named ~ubuntu-xenial_amd64.deb

2017-01-21 11:19 UTC, merged